terrain:
  width: 128
  height: 128

noise:
  type: "perlin" # "perlin" or "fbm"
  scale: 20.0
  octaves: 4  # only used in fbm
  seed: 67
  height_scale: 8.0 

output:
  mesh_dir: "meshes/"
  mesh_name: "terrain.obj"

render:
  cmap: "terrain" # colormap
