terrain:
  width: 128
  height: 128

noise:
  type: "fbm" # "perlin" or "fbm"
  scale: 22.0
  octaves: 4  # only used in fbm
  seed: 67
  height_scale: 12.0

output:
  mesh_dir: "meshes/"
  mesh_name: "terrain.obj"

render:
  cmap: "terrain" # colormap for matplotlib
